"""criando banco

Revision ID: 17fe536d24ea
Revises: 
Create Date: 2025-08-04 00:02:51.355298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17fe536d24ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foto_perfil', sa.String(length=150), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('comum', 'admin', 'autor', name='tipo_usuario_enum'), nullable=False),
    sa.Column('funcao_ministerial', sa.String(length=100), nullable=True),
    sa.Column('igreja_local', sa.String(length=150), nullable=True),
    sa.Column('tempo_ministerio', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tb_plano_estudo',
    sa.Column('id_plano', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('dias_total', sa.Integer(), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['tb_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_plano')
    )
    op.create_table('tb_conteudo_plano',
    sa.Column('id_conteudo', sa.Integer(), nullable=False),
    sa.Column('id_plano', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.Column('conteudo_texto', sa.Text(), nullable=False),
    sa.Column('referencias_biblicas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_plano'], ['tb_plano_estudo.id_plano'], ),
    sa.PrimaryKeyConstraint('id_conteudo')
    )
    op.create_table('tb_usuario_plano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_plano', sa.Integer(), nullable=False),
    sa.Column('dia_atual', sa.Integer(), nullable=True),
    sa.Column('iniciado_em', sa.DateTime(), nullable=True),
    sa.Column('concluido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_plano'], ['tb_plano_estudo.id_plano'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['tb_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_usuario_plano')
    op.drop_table('tb_conteudo_plano')
    op.drop_table('tb_plano_estudo')
    op.drop_table('tb_usuarios')
    # ### end Alembic commands ###
