"""atualizando banco

Revision ID: 7564346ee28b
Revises: 17fe536d24ea
Create Date: 2025-08-07 01:35:55.955772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7564346ee28b'
down_revision = '17fe536d24ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_livro_biblia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('abrev', sa.String(length=10), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abrev')
    )
    op.create_table('tb_versao_biblia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('tb_versiculos_diarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('livro', sa.String(length=20), nullable=True),
    sa.Column('capitulo', sa.Integer(), nullable=True),
    sa.Column('versiculo', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )
    op.create_table('tb_capitulo_biblia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['livro_id'], ['tb_livro_biblia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_devocional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('referencias_biblicas', sa.String(length=100), nullable=True),
    sa.Column('criador_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criador_por'], ['tb_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )
    op.create_table('tb_versiculo_biblia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capitulo_id', sa.Integer(), nullable=True),
    sa.Column('versao_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['capitulo_id'], ['tb_capitulo_biblia.id'], ),
    sa.ForeignKeyConstraint(['versao_id'], ['tb_versao_biblia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_versiculo_biblia')
    op.drop_table('tb_devocional')
    op.drop_table('tb_capitulo_biblia')
    op.drop_table('tb_versiculos_diarios')
    op.drop_table('tb_versao_biblia')
    op.drop_table('tb_livro_biblia')
    # ### end Alembic commands ###
