"""atualizando tabela livro

Revision ID: c8c3b932dbc2
Revises: 7564346ee28b
Create Date: 2025-08-07 14:55:59.500072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c3b932dbc2'
down_revision = '7564346ee28b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_livro_biblia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testamento', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_livro_biblia', schema=None) as batch_op:
        batch_op.drop_column('testamento')

    # ### end Alembic commands ###
